language: r
cache: packages
os: linux
dist: xenial

before_install:
  - sudo apt-get update
  - sudo apt-get -y install libudunits2-dev libgdal-dev

after_success:
  - Rscript -e 'pkgdown::build_site()'
  - git add docs/*

deploy:
  provider: pages
  strategy: git
  cleanup: false
  github_token: $GITHUB_PAT
  keep_history: true
  local_dir: docs
  on:
    branch: travis-test