language: r
cache: packages

before_install:
  - sudo apt-get update
  - sudo apt-get -y install libudunits2-dev

after_success:
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: travis-test