name: Deploy Docs
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
        with:
          Ncpus: 4
      - name: Install dependencies with apt
        run: sudo apt-get -y install libudunits2-dev libgdal-dev
      - uses: r-lib/actions/setup-r-dependencies@v1
      - name: Build documentation
        run: Rscript -e 'pkgdown::build_site()'
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
          user_name: 'openEO CI'
          user_email: openeo.ci@uni-muenster.de